name: trading_journal_pro
description: Trading Journal PRO App
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  uuid: ^4.4.0

flutter:
  uses-material-design: true